on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: batista/lint-filenames@v1.0.1
      - name: Lint Filenames
      with:
        path: 'prod/us/*.yaml'
        pattern: '^[_]*$'

